### ISSUE TITLE
audio: Size element goes left on "Friends' new music" tab of inline player.

### ISSUE THREAD

**Issue by deltaidea** [vk-x/vk-x-legacy#142]
This CSS:

``` CSS
#pad_playlist_panel .wall_module .audio .title_wrap {
    max-width: 290px !important;
    width: auto !important;
}
```

Causes size element which is a child of `.title_wrap` to align on the right of `width: auto` box, hence to move left when the song name is shorter than one full line.
